### PR TITLE
removed 7.2 php support from testing action

### PR DESCRIPTION
**Pull request by sdh100shaun**
| Q                | A
| ---------------- | ---
| Type             | Feature
| Ticket           | n/a

**Description of the change:**
Removed the action testing 7.2 as 7.3 now current minimum requirment.

### CODE REVIEW

**Comment by JoshuaLicense** [comment]
Would it be better to keep supporting PHP 7.2 until it blocks us from doing something (upgrading dependencies etc.)? or maybe a delay until we've moved to PHP 8.0 and remove support for 7.2 & 7.3 at the same time?

**Comment by sdh100shaun** [comment]
> Would it be better to keep supporting PHP 7.2 until it blocks us from doing something (upgrading dependencies etc.)? or maybe a delay until we've moved to PHP 8.0 and remove support for 7.2 & 7.3 at the same time?

it's a choice - my pr suggests my view - remove now largely so we don't have failures from deps etc we have to fix in another PR - but I am easy as to now or later.

**Comment by Hodgy** [comment]
Should we bump the minimum version in composer.json as well if we are removing action

**Comment by sdh100shaun** [comment]
> Should we bump the minimum version in composer.json as well if we are removing action

fair

**Pull request closed without merging**
